version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce-git
        environment:
          APP_DOCKER_IMAGE: amontaigu/terraform
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              make m4 bats
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=app --tag $APP_DOCKER_IMAGE .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $APP_DOCKER_IMAGE
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            export TERRAFORM_VERSION=$(sed -nre 's/^.*TERRAFORM_VERSION="([^"]+)".*$/\1/p;q;' /app/Dockerfile)
            bats /app/tests
