version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.1-ce-git
    environment:
      APP_DOCKER_IMAGE_NAME: amontaigu/terraform
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              bats
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=$APP_DOCKER_IMAGE_NAME --tag $APP_DOCKER_IMAGE_NAME .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar $APP_DOCKER_IMAGE_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            export TERRAFORM_VERSION="$(sed -nre 's/^.*TERRAFORM_VERSION="([^"]+)".*$/\1/p;' Dockerfile | head -1)"
            bats tests
      - deploy:
          name: Push image to Docker hub
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push $APP_DOCKER_IMAGE_NAME $CIRCLE_TAG
            fi